// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqfz0jKnYghxaeKe1TjKrETUqa6Xd0vos',
    appId: '1:1016650343018:web:01952176b7bbdbe4692013',
    messagingSenderId: '1016650343018',
    projectId: 'pictionis-d7fe4',
    authDomain: 'pictionis-d7fe4.firebaseapp.com',
    storageBucket: 'pictionis-d7fe4.appspot.com',
    measurementId: 'G-EW2LJYMRXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_49oee5M-EmOiGi5Eojn1cX6OMfsCHrE',
    appId: '1:1016650343018:android:49f118693288ff25692013',
    messagingSenderId: '1016650343018',
    projectId: 'pictionis-d7fe4',
    storageBucket: 'pictionis-d7fe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39j8aN1_loOfQF3jE6N4pu0TmqkKxsik',
    appId: '1:1016650343018:ios:f7606a494a335ae2692013',
    messagingSenderId: '1016650343018',
    projectId: 'pictionis-d7fe4',
    storageBucket: 'pictionis-d7fe4.appspot.com',
    iosClientId: '1016650343018-7tgpimnhcbe19ko76cdjdcc3nflkjtcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDrawSomething',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39j8aN1_loOfQF3jE6N4pu0TmqkKxsik',
    appId: '1:1016650343018:ios:f7606a494a335ae2692013',
    messagingSenderId: '1016650343018',
    projectId: 'pictionis-d7fe4',
    storageBucket: 'pictionis-d7fe4.appspot.com',
    iosClientId: '1016650343018-7tgpimnhcbe19ko76cdjdcc3nflkjtcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDrawSomething',
  );
}
